# Template variables - filled per personality
# NAME, INITIALS, OUTLET, TITLE, MEDIUMS, SB_PARTNER, SB_ICON, SB_COLOR, SB_BORDER
# OTR_SCORE, RANK, ACCURACY, TAKES, CORRECT, WRONG, PENDING
# SB_SCORE, SB_ACC, SB_TAKES, SB_CORRECT, SB_WRONG
# SPORT_SCORES (NBA/NFL/MLB/NHL)
# BG_COLOR (avatar background)
# SLUG (for filename)
