// OTRScore.com — Site Data
// Replace placeholder content with real data before launch

export const SITE = {
  name: "OTR",
  fullName: "On The Record",
  domain: "OTRScore.com",
  tagline: "Every take. On record. Forever.",
  description: "OTR holds sports media's biggest personalities accountable for every prediction, hot take, and bold call — scored publicly, permanently.",
  sports: ["NFL", "NBA", "MLB", "NHL"],
  launched: "2026",
};

export const PERSONALITIES = [
  {
    id: "bill-simmons",
    name: "Bill Simmons",
    outlet: "The Ringer",
    title: "Founder, The Ringer · NBA on TNT · The Bill Simmons Podcast",
    mediums: ["Podcast", "Column", "TV", "X"],
    sportsbookPartner: "FanDuel",
    otrScore: 791,
    rank: 2,
    accuracy: 61.2,
    totalTakes: 214,
    correct: 131,
    wrong: 83,
    pending: 7,
    trend: 47,
    trendPct: -3,
    sportsbookScore: 341,
    sportsbookAccuracy: 58,
    sportsbookTakes: 67,
    photo: "/images/bill-simmons.jpg",
    sport_breakdown: [
      { sport: "NBA", accuracy: 71, takes: 88 },
      { sport: "NFL", accuracy: 44, takes: 62 },
      { sport: "MLB", accuracy: 58, takes: 40 },
      { sport: "NHL", accuracy: 52, takes: 24 },
    ],
    takes: [
      {
        id: "bs-001",
        quote: "Jayson Tatum will be a top-3 player in the league by the 2026–27 season. I'm not even debating this.",
        source: "The Bill Simmons Podcast",
        sourceEp: "Ep. 1,204",
        date: "Mar 14, 2026",
        sport: "NBA",
        category: "Player Trajectory",
        difficulty: 2.5,
        specificity: 0.85,
        horizon: "multi-season",
        horizonMultiplier: 1.35,
        otrLine: 383,
        verdict: "pending",
        resolves: "Oct 2027",
        sportsbookPartner: null,
      },
      {
        id: "bs-002",
        quote: "The Celtics are a dynasty. Three titles in five years — I'm saying it now.",
        source: "NBA on TNT",
        sourceEp: "Pre-game",
        date: "Jun 3, 2025",
        sport: "NBA",
        category: "Franchise",
        difficulty: 3,
        specificity: 1.0,
        horizon: "era",
        horizonMultiplier: 1.5,
        otrLine: 540,
        verdict: "pending",
        resolves: "Jun 2030",
        sportsbookPartner: null,
      },
      {
        id: "bs-003",
        quote: "Wemby wins Rookie of the Year — it's not even a competition.",
        source: "The Bill Simmons Podcast",
        sourceEp: "Ep. 998",
        date: "Oct 2023",
        sport: "NBA",
        category: "Player",
        difficulty: 1.5,
        specificity: 0.9,
        horizon: "season",
        horizonMultiplier: 1.2,
        otrLine: 216,
        verdict: "correct",
        resolvedDate: "Apr 2024",
        sportsbookPartner: null,
      },
      {
        id: "bs-004",
        quote: "The Lakers make the conference finals — LeBron is still that guy.",
        source: "The Bill Simmons Podcast",
        sourceEp: "Ep. 1,100",
        date: "Oct 2024",
        sport: "NBA",
        category: "Playoff",
        difficulty: 2,
        specificity: 0.8,
        horizon: "season",
        horizonMultiplier: 1.2,
        otrLine: 189,
        verdict: "wrong",
        resolvedDate: "May 2025",
        sportsbookPartner: null,
      },
      {
        id: "bs-005",
        quote: "Taking the Celtics to cover tonight. No-brainer. #FanDuelPartner",
        source: "X @BillSimmons",
        date: "Mar 28, 2026",
        sport: "NBA",
        category: "Game",
        difficulty: 1,
        specificity: 1.0,
        horizon: "game",
        horizonMultiplier: 1.0,
        otrLine: 82,
        verdict: "correct",
        resolvedDate: "Mar 28, 2026",
        sportsbookPartner: "FanDuel",
        odds: "-220",
      },
    ],
    hof: {
      greatestCall: {
        quote: "Giannis wins back-to-back MVPs and a title before he turns 30. He is the best player on the planet and it isn't close.",
        context: "Oct 2018 · The Ringer · Wild (3×) · Era call",
        score: 486,
      },
      worstCall: {
        quote: "Brooklyn has the best roster I've ever seen assembled in my lifetime. They win the title this year, next year, and the year after. It's a wrap.",
        context: "Sep 2021 · Podcast · Wild (3×) · Deleted tweet",
        score: -560,
      },
      bestStreak: {
        description: "7 consecutive correct calls — NBA Draft 2022 through NBA Finals 2023.",
        context: "Jun 2022 – Jun 2023 · Mixed sources",
        score: 1204,
      },
      coldestStretch: {
        description: "4 wrong calls in 6 weeks during the 2024 NFL season — all involving the Patriots rebuild.",
        context: "Oct – Nov 2024 · The Bill Simmons Podcast",
        score: -612,
      },
    },
    accountability: {
      corrections: 8,
      deletedPosts: 3,
      integrityScore: 44,
    },
    headToHead: [
      { opponent: "Russillo", wins: 8, losses: 10 },
      { opponent: "Cowherd", wins: 14, losses: 6 },
      { opponent: "S.A. Smith", wins: 11, losses: 6 },
      { opponent: "Portnoy", wins: 16, losses: 4 },
      { opponent: "Big Cat", wins: 5, losses: 7 },
    ],
  },
  // Additional personalities will be added here
  {
    id: "ryen-russillo",
    name: "Ryen Russillo",
    outlet: "Barstool Sports",
    title: "The Ryen Russillo Podcast · Barstool Sports",
    mediums: ["Podcast", "TV", "X"],
    sportsbookPartner: "FanDuel",
    otrScore: 847,
    rank: 1,
    accuracy: 68.4,
    totalTakes: 198,
    correct: 136,
    wrong: 62,
    pending: 9,
    trend: 12,
    trendPct: 12,
    sportsbookScore: 188,
    sportsbookAccuracy: 64,
    sportsbookTakes: 41,
    photo: "/images/ryen-russillo.jpg",
    sport_breakdown: [
      { sport: "NBA", accuracy: 74, takes: 102 },
      { sport: "NFL", accuracy: 61, takes: 58 },
      { sport: "MLB", accuracy: 55, takes: 24 },
      { sport: "NHL", accuracy: 48, takes: 14 },
    ],
    takes: [],
    hof: null,
    accountability: { corrections: 11, deletedPosts: 1, integrityScore: 82 },
    headToHead: [],
  },
  {
    id: "colin-cowherd",
    name: "Colin Cowherd",
    outlet: "Fox Sports",
    title: "The Herd with Colin Cowherd · Fox Sports Radio",
    mediums: ["TV", "Podcast", "Radio", "X"],
    sportsbookPartner: "FanDuel",
    otrScore: 734,
    rank: 3,
    accuracy: 58.8,
    totalTakes: 312,
    correct: 184,
    wrong: 128,
    pending: 14,
    trend: 8,
    trendPct: 6,
    sportsbookScore: 92,
    sportsbookAccuracy: 54,
    sportsbookTakes: 88,
    photo: "/images/colin-cowherd.jpg",
    sport_breakdown: [
      { sport: "NFL", accuracy: 63, takes: 148 },
      { sport: "NBA", accuracy: 54, takes: 96 },
      { sport: "MLB", accuracy: 52, takes: 44 },
      { sport: "NHL", accuracy: 44, takes: 24 },
    ],
    takes: [],
    hof: null,
    accountability: { corrections: 4, deletedPosts: 7, integrityScore: -18 },
    headToHead: [],
  },
  {
    id: "stephen-a-smith",
    name: "Stephen A. Smith",
    outlet: "ESPN",
    title: "First Take · The Stephen A. Smith Show",
    mediums: ["TV", "Podcast", "X"],
    sportsbookPartner: null,
    otrScore: 612,
    rank: 4,
    accuracy: 49.1,
    totalTakes: 441,
    correct: 217,
    wrong: 224,
    pending: 22,
    trend: -19,
    trendPct: -11,
    sportsbookScore: null,
    sportsbookAccuracy: null,
    sportsbookTakes: null,
    photo: "/images/stephen-a-smith.jpg",
    sport_breakdown: [
      { sport: "NBA", accuracy: 54, takes: 198 },
      { sport: "NFL", accuracy: 46, takes: 144 },
      { sport: "MLB", accuracy: 41, takes: 62 },
      { sport: "NHL", accuracy: 38, takes: 37 },
    ],
    takes: [],
    hof: null,
    accountability: { corrections: 2, deletedPosts: 14, integrityScore: -88 },
    headToHead: [],
  },
  {
    id: "big-cat",
    name: "Big Cat",
    outlet: "Barstool Sports",
    title: "Pardon My Take · Barstool Sports",
    mediums: ["Podcast", "TV", "X"],
    sportsbookPartner: "DraftKings",
    otrScore: 589,
    rank: 5,
    accuracy: 52.3,
    totalTakes: 276,
    correct: 144,
    wrong: 132,
    pending: 11,
    trend: -22,
    trendPct: -8,
    sportsbookScore: -290,
    sportsbookAccuracy: 35,
    sportsbookTakes: 94,
    photo: "/images/big-cat.jpg",
    sport_breakdown: [
      { sport: "NFL", accuracy: 58, takes: 128 },
      { sport: "NBA", accuracy: 48, takes: 74 },
      { sport: "MLB", accuracy: 52, takes: 48 },
      { sport: "NHL", accuracy: 44, takes: 26 },
    ],
    takes: [],
    hof: null,
    accountability: { corrections: 6, deletedPosts: 4, integrityScore: 12 },
    headToHead: [],
  },
  {
    id: "dave-portnoy",
    name: "Dave Portnoy",
    outlet: "Barstool Sports",
    title: "Barstool Sports Founder · One Bite · Emergency Podcast",
    mediums: ["Podcast", "TV", "X"],
    sportsbookPartner: "DraftKings",
    otrScore: 544,
    rank: 6,
    accuracy: 38.2,
    totalTakes: 188,
    correct: 72,
    wrong: 116,
    pending: 6,
    trend: -31,
    trendPct: -18,
    sportsbookScore: -380,
    sportsbookAccuracy: 31,
    sportsbookTakes: 112,
    photo: "/images/dave-portnoy.jpg",
    sport_breakdown: [
      { sport: "NFL", accuracy: 40, takes: 88 },
      { sport: "NBA", accuracy: 36, takes: 54 },
      { sport: "MLB", accuracy: 38, takes: 32 },
      { sport: "NHL", accuracy: 36, takes: 14 },
    ],
    takes: [],
    hof: null,
    accountability: { corrections: 1, deletedPosts: 22, integrityScore: -148 },
    headToHead: [],
  },
];

export const LEADERBOARD = PERSONALITIES.sort((a, b) => b.otrScore - a.otrScore);

export const TICKER_ITEMS = [
  { personality: "Cowherd", call: "Celtics dynasty call", verdict: "correct", points: 42 },
  { personality: "S.A. Smith", call: "Bronny top 5 pick", verdict: "wrong", points: -28 },
  { personality: "Simmons", call: "Wemby ROTY", verdict: "correct", points: 216 },
  { personality: "Portnoy", call: "Chiefs 3-peat", verdict: "wrong", points: -540 },
  { personality: "Russillo", call: "Lakers miss playoffs", verdict: "correct", points: 33 },
  { personality: "Big Cat", call: "Bears win 12 games", verdict: "wrong", points: -41 },
  { personality: "Simmons", call: "Celtics cover −220", verdict: "correct", points: 82 },
  { personality: "Portnoy", call: "Knicks +7.5 live bet", verdict: "wrong", points: -248 },
];
